apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cmpt756s2
spec:
  host: cmpt756s2
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 5
      http:
        http1MaxPendingRequests: 5
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
